name: Propagate template changes

on: [push]

jobs:
  propagate:
    name: Propagate template changes
    # Most likely you don't want to run this action on the template forks
    if: github.repository == 'Joao-1/CountryData'
    runs-on: ubuntu-latest
    steps:
    - uses: tenpureto/propagate-changes-action@v1
      with:
        pull-request-label: pr:propagating-changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}